Added jacoco plugin for test coverage
fungover/mmotodo pull request #44
Opened 2023-12-24 09:45 UTC by ved0

* Update pom.xml with jacoco plugin (creates an html file with the coverage report)

Merry Christmas everyone!

2023-12-25 08:56 UTC, Arash-SJPI22 commented
Good decition, merry x-mas :D

2023-12-25 08:56 UTC, Arash-SJPI22 approved these changes
Good decision, merry x-mas :D
:+1:

2023-12-27 09:10 UTC, saeraa commented
It's a great idea to add this, however only creating a html page with it doesn't help us unless we go and look at the html page afterwards. How about adding a minimum coverage requirement and then run `mvn clean verify` when the project is updated to ensure they are met?

2023-12-27 10:17 UTC, kappsegla requested changes

2023-12-27 10:57 UTC, kappsegla approved these changes

2023-12-27 10:58 UTC, merged